// <copyright file="Leaderboards.cs" company="Jan Ivar Z. Carlsen, Sindri Jóelsson">
// Copyright (c) 2016 Jan Ivar Z. Carlsen, Sindri Jóelsson. All rights reserved.
// Licensed under the MIT license. See LICENSE file in the project root for full license information.
// </copyright>

namespace CloudOnce
{
    using System.Collections.Generic;
    using Internal;

    /// <summary>
    /// Provides access to leaderboards registered via the CloudOnce Editor.
    /// This file was automatically generated by CloudOnce. Do not edit.
    /// </summary>
    public static class Leaderboards
    {
        private static readonly UnifiedLeaderboard s_world1 = new UnifiedLeaderboard("world1",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "world1"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI_O_WpbYSEAIQAQ"
#else
            "world1"
#endif
            );

        public static UnifiedLeaderboard world1
        {
            get { return s_world1; }
        }

        private static readonly UnifiedLeaderboard s_world2 = new UnifiedLeaderboard("world2",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "world2"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI_O_WpbYSEAIQAg"
#else
            "world2"
#endif
            );

        public static UnifiedLeaderboard world2
        {
            get { return s_world2; }
        }

        private static readonly UnifiedLeaderboard s_world3 = new UnifiedLeaderboard("world3",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "wolrd3"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI_O_WpbYSEAIQAw"
#else
            "world3"
#endif
            );

        public static UnifiedLeaderboard world3
        {
            get { return s_world3; }
        }

        private static readonly UnifiedLeaderboard s_world4 = new UnifiedLeaderboard("world4",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "world4"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI_O_WpbYSEAIQBA"
#else
            "world4"
#endif
            );

        public static UnifiedLeaderboard world4
        {
            get { return s_world4; }
        }

        private static readonly UnifiedLeaderboard s_world5 = new UnifiedLeaderboard("world5",
#if !UNITY_EDITOR && (UNITY_IOS || UNITY_TVOS)
            "world5"
#elif !UNITY_EDITOR && UNITY_ANDROID && CLOUDONCE_GOOGLE
            "CgkI_O_WpbYSEAIQBQ"
#else
            "world5"
#endif
            );

        public static UnifiedLeaderboard world5
        {
            get { return s_world5; }
        }

        public static string GetPlatformID(string internalId)
        {
            return s_leaderboardDictionary.ContainsKey(internalId)
                ? s_leaderboardDictionary[internalId].ID
                : string.Empty;
        }

        private static readonly Dictionary<string, UnifiedLeaderboard> s_leaderboardDictionary = new Dictionary<string, UnifiedLeaderboard>
        {
            { "world1", s_world1 },
            { "world2", s_world2 },
            { "world3", s_world3 },
            { "world4", s_world4 },
            { "world5", s_world5 }
        };
    }
}
